CREATE TABLESPACE SCPODATA
  DATAFILE 'SCPODATA.dat' 
    SIZE 200M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 2000M
  ONLINE;

CREATE TABLESPACE SCPODINDEX
  DATAFILE 'SCPOINDEX.dat' 
    SIZE 200M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 2000M
  ONLINE;

CREATE TABLESPACE EMADATA
  DATAFILE 'EMADATA.dat' 
    SIZE 200M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 2000M
  ONLINE;