GRANT SELECT_CATALOG_ROLE TO ABPPMGR;
GRANT CREATE SESSION TO ABPPMGR;
GRANT CREATE TABLE TO ABPPMGR;
GRANT CREATE VIEW TO ABPPMGR;
GRANT CREATE PROCEDURE TO ABPPMGR;
GRANT CREATE TRIGGER TO ABPPMGR;
GRANT CREATE SEQUENCE TO ABPPMGR;
GRANT CREATE SYNONYM TO ABPPMGR;
GRANT CREATE MATERIALIZED VIEW TO ABPPMGR;